task_id: ""
data:
  root: "../data/"
  dataset: cifar10
  split_type: "class" 
  # 数据集分发方式，选项：iid，niid，dir，class
  # iid 独立同分布
  # niid 非独立同分布
  # dir 用于模拟 CIFAR-10 和 CIFAR-100 数据集的非独立同分布数据的 Dirichlet 过程。
  # class 按标签类别分发数据集
  
  min_size: 10 # 每个客户端的最小样本数
  data_amount: 0.05 # LEAF数据集专用选项
  iid_fraction: 0.1 # iid选项专用
  user: False # 只适用于femnist和shakespeare数据集
  
  class_per_client: 8 # 每个客户端的类别，只有当split_type是'class'时有用
  num_of_clients: 10
  train_test_split: 0.8  
  alpha: 0.2 # Dirichlet 过程的参数
  
  weights: NULL
  
model: simple_cnn
test_mode: "test_in_client"
test_method: "average"

server:
  track: False
  rounds: 300 # 总的训练轮数
  clients_per_round: 2 # 每轮选择的客户端数量
  test_every: 1
  save_model_every: 10
  save_model_path: ""
  batch_size: 64
  test_all: True
  random_selection: True
  aggregation_stragtegy: "FedAvg"
  aggregation_content: "all"

client:
  track: False
  batch_size: 16
  test_batch_size: 5
  local_epoch: 20
  optimizer:
    type: "SGD"
    lr: 0.01
    momentum: 0.5
    weight_decay: 5e-4
    nesterov: True
  seed: 0
  local_test: True

gpu: 1
distributed:
  backend: "nccl"
  init_method: ""
  world_size: 0
  rank: 0
  local_rank: 0

tracking:
  database: ""
  log_file: ""
  log_level: "INFO"
  metric_file: ""
  save_every: 1

resource_heterogeneous:
  simulate: False
  hetero_type: "real"
  level: 3
  sleep_group_num: 1000
  total_time: 1000
  fraction: 1
  grouping_strategy: "greedy"
  initial_default_time: 5
  default_time_momentum: 0.2

seed: 0  